server {
  listen 4173;
  server_name _;

  root /usr/share/nginx/html;

  location = /state-layers {
    return 301 /state-layers/;
  }

  location /state-layers/assets/ {
    try_files $uri =404;
  }

  location /state-layers/ {
    try_files $uri $uri/ /state-layers/index.html;
  }

  location / {
    return 404;
  }
}
